# Generated by Django 4.1 on 2022-08-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default='temp', max_length=100),
        ),
    ]
