# Generated by Django 4.1 on 2022-08-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Employee_ID_Number',
            field=models.CharField(max_length=100),
        ),
    ]
