# Generated by Django 4.1 on 2022-08-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authApp', '0003_alter_user_employee_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, null=True)),
                ('basePrice', models.FloatField()),
                ('curPrice', models.FloatField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.user')),
            ],
        ),
    ]
