# Generated by Django 4.1 on 2022-08-24 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_user_employee_id_number'),
        ('bidding', '0005_alter_product_image1'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevPrice', models.FloatField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.product')),
            ],
        ),
    ]
