# Generated by Django 4.1 on 2022-08-25 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0006_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deadline',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
