# Generated by Django 4.1 on 2022-08-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0007_product_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
