# Generated by Django 4.1 on 2022-08-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0008_alter_product_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='curPrice',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
    ]
