# Generated by Django 4.1 on 2022-08-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0010_alter_bid_bidder_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
