# Generated by Django 4.1 on 2022-08-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0011_product_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='successfull',
            field=models.BooleanField(default=False),
        ),
    ]
