# Generated by Django 4.1 on 2022-08-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0013_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
